import type { AuditContext, SecurityCheck, Finding, AuditFile } from './types.js';
import { finding, isSecretFile, lineOf } from './utils.js';

const rules = (name: string) => (f: AuditFile) => /(^|\/)(firestore|storage)\.rules$/i.test(f.relativePath) && f.relativePath.toLowerCase().includes(name);
const firebaseDocs = 'https://firebase.google.com/docs/rules';
const checks: SecurityCheck[] = [
  { id: 'firestore-public-access', description: 'Detect public Firestore read/write rules', run: c => c.files.filter(rules('firestore')).flatMap(f => [...f.content.matchAll(/allow\s+(read|write|read,\s*write)\s*:\s*if\s+true\s*;/gi)].map(m => finding(f, { id: 'firestore-public-access', title: 'Public Firestore access', severity: 'Critical', line: lineOf(f, m[0]), reason: 'This rule grants access to every client without authentication or authorization.', example: m[0], remediation: 'Require authentication and validate access to the specific document or query.', reference: firebaseDocs }))) },
  { id: 'storage-public-access', description: 'Detect public Cloud Storage rules', run: c => c.files.filter(rules('storage')).flatMap(f => [...f.content.matchAll(/allow\s+(read|write|read,\s*write)\s*:\s*if\s+true\s*;/gi)].map(m => finding(f, { id: 'storage-public-access', title: 'Public Storage access', severity: 'Critical', line: lineOf(f, m[0]), reason: 'Anyone who can reach the bucket can read or modify objects.', example: m[0], remediation: 'Require signed-in users and validate path ownership, content type, and size.', reference: 'https://firebase.google.com/docs/storage/security' }))) },
  { id: 'unauthenticated-rules', description: 'Find rules that explicitly allow unauthenticated access', run: c => c.files.filter(f => /(^|\/)(firestore|storage)\.rules$/i.test(f.relativePath)).flatMap(f => [...f.content.matchAll(/allow\s+\w+\s*:\s*if\s+(request\.auth\s*==\s*null|true)\s*;/gi)].filter(m => !/true\s*;/i.test(m[0])).map(m => finding(f, { id: 'unauthenticated-rules', title: 'Unauthenticated rule path', severity: 'High', line: lineOf(f, m[0]), reason: 'The rule explicitly permits requests with no Firebase Auth context.', example: m[0], remediation: 'Require request.auth and apply authorization checks for the resource.', reference: firebaseDocs }))) },
  { id: 'wildcard-write', description: 'Find broad wildcard writes', run: c => c.files.filter(f => /(^|\/)(firestore|storage)\.rules$/i.test(f.relativePath)).flatMap(f => [...f.content.matchAll(/match\s+\/(?:\*\*|\{[^}]+\})[\s\S]{0,300}?allow\s+write\s*:/gi)].map(m => finding(f, { id: 'wildcard-write', title: 'Broad wildcard write permission', severity: 'High', line: lineOf(f, 'allow\\s+write'), reason: 'A write permission under a broad match can expose more data than intended.', example: m[0].replace(/\s+/g, ' ').slice(0, 180), remediation: 'Narrow the match path and split create, update, and delete authorization.', reference: firebaseDocs }))) },
  { id: 'missing-storage-validation', description: 'Find Storage writes without validation', run: c => c.files.filter(rules('storage')).filter(f => /allow\s+write/i.test(f.content) && !/request\.resource\.(size|contentType)/i.test(f.content)).map(f => finding(f, { id: 'missing-storage-validation', title: 'Storage upload lacks validation', severity: 'Medium', line: lineOf(f, /allow\s+write/i), reason: 'Uploads are not checked for size or content type, increasing abuse and malware risk.', example: 'allow write: if request.auth != null;', remediation: 'Validate request.resource.size and request.resource.contentType before accepting uploads.', reference: 'https://firebase.google.com/docs/storage/security/rules-conditions' })) },
  { id: 'anonymous-auth', description: 'Detect enabled anonymous authentication configuration', run: c => c.files.filter(f => /(^|\/)firebase\.json$/i.test(f.relativePath)).filter(f => /anonymous/i.test(f.content)).map(f => finding(f, { id: 'anonymous-auth', title: 'Anonymous authentication is configured', severity: 'Low', line: lineOf(f, /anonymous/i), reason: 'Anonymous accounts can be useful, but unbounded use may enable abuse and cost growth.', example: 'anonymous: true', remediation: 'Enable only when needed, link accounts, enforce quotas/App Check, and monitor abuse.', reference: 'https://firebase.google.com/docs/auth/web/anonymous-auth' })) },
  { id: 'hosting-security-headers', description: 'Detect missing common Hosting security headers', run: c => c.files.filter(f => /(^|\/)firebase\.json$/i.test(f.relativePath)).filter(f => /hosting/i.test(f.content) && !/headers/i.test(f.content)).map(f => finding(f, { id: 'hosting-security-headers', title: 'Hosting security headers are not configured', severity: 'Medium', line: lineOf(f, /hosting/i), reason: 'The Hosting configuration has no explicit security headers such as CSP or frame protections.', example: 'hosting: { public: "dist" }', remediation: 'Add a restrictive Content-Security-Policy, X-Content-Type-Options, Referrer-Policy, and frame policy suited to the app.', reference: 'https://firebase.google.com/docs/hosting/full-config' })) },
  { id: 'app-check-not-configured', description: 'Flag projects without visible App Check configuration', run: c => c.files.some(f => /(^|\/)firebase\.json$/i.test(f.relativePath)) && !c.files.some(f => /app.?check|appCheck/i.test(f.content)) ? [{ id: 'app-check-not-configured', title: 'App Check configuration not found', severity: 'Info', file: 'firebase.json', reason: 'No App Check configuration was found in local project files; enforcement may still be configured in the console.', example: 'No local App Check configuration detected', remediation: 'Consider App Check for supported Firebase services and verify enforcement in the Firebase console.', reference: 'https://firebase.google.com/docs/app-check' }] : [] },
  { id: 'exposed-secrets', description: 'Detect secret-like files and values', run: c => c.files.filter(f => isSecretFile(f.relativePath) || /(?:private_key|client_secret|password|api[_-]?key)\s*[:=]\s*['"][^'"]{12,}/i.test(f.content)).map(f => finding(f, { id: 'exposed-secrets', title: 'Potential secret in project files', severity: 'Critical', line: lineOf(f, /(?:private_key|client_secret|password|api[_-]?key)/i), reason: 'Credential-like material appears in a file that may be committed or shipped.', example: isSecretFile(f.relativePath) ? f.relativePath : 'credential-like assignment', remediation: 'Remove it from source control, rotate it, add the file to .gitignore, and use a secret manager or environment injection.', reference: 'https://firebase.google.com/docs/functions/config-env' })) },
  { id: 'firebase-api-key', description: 'Detect Firebase web API keys and unsafe client config', run: c => c.files.filter(f => /\.(js|ts|json|jsx|tsx)$/i.test(f.relativePath)).flatMap(f => [...f.content.matchAll(/AIza[0-9A-Za-z_-]{20,}/g)].map(m => finding(f, { id: 'firebase-api-key', title: 'Firebase API key found', severity: 'Low', line: lineOf(f, m[0]), reason: 'A Firebase web API key is present. These keys are identifiers, but should be restricted and monitored.', example: m[0].slice(0, 10) + '…', remediation: 'Restrict the key by API and application, keep security in Auth/Rules, and rotate if it was intended to be secret.', reference: 'https://firebase.google.com/docs/projects/api-keys' }))) },
  { id: 'cors-wildcard', description: 'Detect wildcard CORS configuration in functions', run: c => c.files.filter(f => /\.(js|ts|json)$/i.test(f.relativePath) && /functions?\//i.test(f.relativePath)).filter(f => /cors\s*\([^)]*\*|origin\s*:\s*['"]\*['"]|Access-Control-Allow-Origin['"]?\s*[:=]\s*['"]\*['"]/i.test(f.content)).map(f => finding(f, { id: 'cors-wildcard', title: 'Wildcard CORS origin', severity: 'Medium', line: lineOf(f, /cors|Access-Control-Allow-Origin/i), reason: 'Any website may be allowed to call the function from a browser context.', example: "cors({ origin: '*' })", remediation: 'Allow only trusted origins and enforce authentication/authorization server-side.', reference: 'https://owasp.org/www-community/attacks/CORS_OriginHeaderScrutiny' })) },
  { id: 'client-trust', description: 'Detect server code trusting client-provided admin flags', run: c => c.files.filter(f => /functions?\//i.test(f.relativePath) && /\.(js|ts)$/i.test(f.relativePath)).filter(f => /data\.(isAdmin|role|admin)|req\.body\.(isAdmin|role|admin)/i.test(f.content)).map(f => finding(f, { id: 'client-trust', title: 'Authorization appears to trust client data', severity: 'High', line: lineOf(f, /data\.(isAdmin|role|admin)|req\.body\.(isAdmin|role|admin)/i), reason: 'Client-controlled request data can be modified and must not decide privileged access.', example: 'if (data.isAdmin) { ... }', remediation: 'Derive authorization from verified Auth tokens, custom claims, and server-side data; validate all inputs.', reference: 'https://firebase.google.com/docs/auth/admin/verify-id-tokens' })) },
  { id: 'admin-sdk-client', description: 'Detect Admin SDK usage in browser-like source', run: c => c.files.filter(f => /\.(html|jsx|tsx)$/i.test(f.relativePath)).filter(f => /firebase-admin|admin\.initializeApp/i.test(f.content)).map(f => finding(f, { id: 'admin-sdk-client', title: 'Admin SDK reference in client source', severity: 'Critical', line: lineOf(f, /firebase-admin|admin\.initializeApp/i), reason: 'The Admin SDK is privileged and must never be bundled into untrusted client code.', example: 'import admin from "firebase-admin"', remediation: 'Move Admin SDK code to trusted server-side functions and never ship service-account credentials.', reference: 'https://firebase.google.com/docs/admin/setup' })) },
];
export function getChecks(): SecurityCheck[] { return checks; }
export function runChecks(context: AuditContext, selected = checks): Finding[] { return selected.flatMap(check => check.run(context)); }
